inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15
