source 'https://rubygems.org'

ruby '3.4.5'

gem 'active_storage_validations'

gem 'bootsnap', require: false
gem 'brakeman', require: false

gem 'cancancan', '~> 3.6'
gem 'clearance', '~> 2.6'
gem 'countries'
gem 'country_select'

gem 'dartsass-rails'
gem 'debug', platforms: %i(mri windows), require: 'debug/prelude'

gem 'erb-formatter', '~> 0.7.3'

gem 'image_processing', '~> 1.2'
gem 'importmap-rails'

gem 'pg', '>= 1.5', '< 2.0'
gem 'propshaft'
gem 'puma', '>= 5.0'

gem 'rails', '~> 8.0.2', '>= 8.0.2.1'
gem 'rubocop', require: false
gem 'rubocop-erb', require: false
gem 'rubocop-factory_bot', '~> 2.27', '>= 2.27.1'
gem 'rubocop-rails', require: false
gem 'rubocop-rspec', '~> 3.7'
gem 'rubocop-rspec_rails', '~> 2.31'
gem 'ruby-vips'

group :development do
  gem 'i18n-tasks', '~> 1.0.15'
  gem 'web-console'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
end

gem 'erb-formatter', '~> 0.7.3'
