# Gemfile
source 'https://rubygems.org'

ruby '3.4.5'
gem 'pg', '>= 1.5', '< 2.0'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.0.2', '>= 8.0.2.1'

gem 'cancancan', '~> 3.6'
gem 'clearance', '~> 2.6'

gem 'bootsnap', require: false
gem 'brakeman', require: false
gem 'debug', platforms: %i(mri windows), require: 'debug/prelude'

gem 'rubocop', require: false
gem 'rubocop-rails', require: false

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
end
