# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: journey_development

test:
  <<: *default
  database: journey_test

production:
  <<: *default
  # meist via ENV: DATABASE_URL